# Generated by Django 5.2.1 on 2025-06-06 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0002_donationcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodCompatibility',
        ),
        migrations.DeleteModel(
            name='DonationCenter',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='collector',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='license_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Latitude,Longitude format', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='staff_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
