# Generated by Django 5.2.1 on 2025-06-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0006_donationappointment_collector_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('registered_donors', models.PositiveIntegerField(default=0)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_drives', to='bload_donor_app.collector')),
            ],
        ),
    ]
