# Generated by Django 5.2.1 on 2025-06-07 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0007_donationdrive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdrive',
            name='location',
        ),
        migrations.RemoveField(
            model_name='donationdrive',
            name='registered_donors',
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bload_donor_app.donationdrive'),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bload_donor_app.collector'),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='time',
            field=models.TimeField(),
        ),
    ]
