# Generated by Django 5.2.1 on 2025-06-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0003_delete_bloodcompatibility_delete_donationcenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='operating_hours',
        ),
    ]
