# Generated by Django 5.2.1 on 2025-06-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0004_remove_collector_operating_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationappointment',
            old_name='location',
            new_name='selected_center',
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bload_donor_app.collector'),
        ),
    ]
