# Generated by Django 5.2.1 on 2025-06-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0005_rename_location_donationappointment_selected_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationappointment',
            name='collector_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='donor_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bload_donor_app.collector'),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='selected_center',
            field=models.CharField(max_length=255),
        ),
    ]
