# Generated by Django 5.2.1 on 2025-06-09 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0008_remove_donationdrive_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='selected_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
