# Generated by Django 5.2.1 on 2025-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0010_remove_donor_donated_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='has_donated_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_before_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
